### ISSUE TITLE
Error message when importing

### ISSUE THREAD

**Issue by chozelinek** [smilli/py-corenlp#2]
I try to import the module but I get this error. I am sure it must be something easy to fix, but I don't write modules/packages. I've followed the instructions in the README file. I am working in a virtual environment. I am using python 3.5.1

I've tried:

``` python
from corenlp import StanfordCoreNLP
```

And it yields:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'corenlp'
```

If I try:

``` python
from pycorenlp import StanfordCoreNLP
```

I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmmmac/.virtualenvs/traditools3/lib/python3.5/site-packages/pycorenlp/__init__.py", line 1, in <module>
    from corenlp import StanfordCoreNLP
ImportError: No module named 'corenlp'
```

**Comment by chozelinek** [comment]
My solution, although I don't know if this is the appropriate way of doing it, but it works.

In file pycorenlp/**init**.py remove the content.

Then:

``` python
from pycorenlp.corenlp import StanfordCoreNLP
```

The rest of your example works as described.

**Comment by smilli** [comment]
Sorry, it wasn't working in Python3!  Thanks, just fixed and updated the docs.  You should be able to use `from pycorenlp import StanfordCoreNLP` now.
