### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by jchen812** [smilli/py-corenlp#32]
Hi, I am following the Usage part in the README, when I am running `print(output['sentences'][0]['parse'])`, it gives me error TypeError: string indices must be integers.
I think that's because there is something wrong with the variable -- output. What is going wrong?

It looks like`'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<!-- FileName: index.html\n     Language: [en]\n-->\n<!--Head-->\n<head>\n  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">\n  <meta http-equiv="X-UA-Compatible" content="IE=7" />\n  <title>McAfee Web Gateway - Notification</title>\n  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>\n  <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />\n</head>\n<!--/Head-->\n<!--Body-->\n<body onload="swOnLoad();">\n  <table class=\'bodyTable\'>\n    <tr>\n      <td class=\'bodyData\' background=\'/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif\'>\n<!--Logo-->\n<table class=\'logoTable\'>\n  <tr>\n    <td class=\'logoData\'>\n      <a href=\'http://www.americanexpress.com\'>\n        <img src=\'/mwg-internal/de5fs23hu73ds/files/default/img/blue_box.png\'></a>\n    </td>\n  </tr>\n</table>\n<!--/Logo-->\n<!--Contents-->\n<!-- FileName: URLBlocked.html\n     Language: [en]\n-->\n<!--Title-->\n<table class=\'titleTable\' background=\'/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg\'>\n  <tr>\n    <td class=\'titleData\'>\n      American Express Acceptable Use Policy\n    </td>\n  </tr>\n</table>\n<!--/Title-->\n\n<!--Content-->\n<table class="contentTable">\n  <tr>\n    <td class="contentData">\n  Access to the requested website is restricted because it may violate the <a href=\'https://square.aexp.com/StaffGroups/Technologies/ToolsandServices/ISPoliciesandStandardsLibrary/Pages/ISPolicies-StandardsLibrary_4797.aspx\'>Acceptable Use Policy</a> and/or the <a href=\'https://square.aexp.com/StaffGroups/GCO/CodeofConduct/Pages/MyCode_109.aspx\'>American Express Code of Conduct</a> and/or  represent a malware risk to the company.\n<br><br>\nPlease note that per company policy, Internet activity is monitored and inappropriate activity may be subject to disciplinary action.\n<br><br>\nTo obtain access for business purposes or to request a site review, please submit a Web Exception Request via <a href=\'https://amexitsm.service-now.com/amex/catalog_content.do?sysparm_document_key=sc_cat_item,8bdebf7a6f5a15008954ad32be3ee4a0&uri=com.glideapp.servicecatalog_cat_item_view_amex.do%3Fsysparm_id%3D8bdebf7a6f5a15008954ad32be3ee4a0%26sysparm_no_search%3Dtrue\'>ServiceNow.  </a> <br /><br/><br/><br/>\n    </td>\n  </tr>\n</table>\n<!--/Content-->\n\n<!--Info-->\n<table class=\'infoTable\'>\n<tr>\n    <td class=\'infoData\'>\n<hr><br>\nURL: <script type="text/javascript">break_line("http://localhost:9000/?properties=%7B%27annotators%27%3A+%27tokenize%2Cssplit%2Cpos%2Cdepparse%2Cparse%27%2C+%27outputFormat%27%3A+%27json%27%7D");</script>\n<script type="text/javascript">writeToDocument("URL Categories:" + "" );</script> Reputation: Unverified\n     User Name: jchen81 <br>\n    </td>\n  </tr>\n</table>\n     \n\n<!--/Info-->\n<!--/Contents-->\n\n<!--Foot-->\n<table class=\'footTable\'>\n  <tr>\n    <td class=\'helpDeskData\' background=\'/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg\'>\n      For additional assistance, please contact your local technologies helpdesk.\n    </td>\n  </tr>\n  <tr>\n    <td class=\'footData\'>\n      generated <span id="time">2018-07-06 18:44:54</span> by NYCWFCUPXY04\n    </td>\n  </tr>\n</table>\n<!--/Foot-->\n      </td>\n    </tr>\n  </table>\n</body>\n<!--/Body-->\n</html>\n'`

**Comment by RolfLobo** [comment]
Hey,
Did you manage to resolve this issue?
